// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemRetribusiParkir.Data;

#nullable disable

namespace SistemRetribusiParkir.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260705142527_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemRetribusiParkir.Models.JenisKendaraan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Keterangan")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NamaJenis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Tarif")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("JenisKendaraan");
                });

            modelBuilder.Entity("SistemRetribusiParkir.Models.LokasiParkir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("int");

                    b.Property<string>("NamaLokasi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("LokasiParkir");
                });

            modelBuilder.Entity("SistemRetribusiParkir.Models.Petugas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NamaPetugas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NoHp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Petugas");
                });

            modelBuilder.Entity("SistemRetribusiParkir.Models.Retribusi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JenisKendaraanId")
                        .HasColumnType("int");

                    b.Property<decimal>("JumlahBayar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("LokasiParkirId")
                        .HasColumnType("int");

                    b.Property<string>("NomorKendaraan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PetugasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Tarif")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("JenisKendaraanId");

                    b.HasIndex("LokasiParkirId");

                    b.HasIndex("PetugasId");

                    b.ToTable("Retribusi");
                });

            modelBuilder.Entity("SistemRetribusiParkir.Models.Retribusi", b =>
                {
                    b.HasOne("SistemRetribusiParkir.Models.JenisKendaraan", "JenisKendaraan")
                        .WithMany("Retribusi")
                        .HasForeignKey("JenisKendaraanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemRetribusiParkir.Models.LokasiParkir", "LokasiParkir")
                        .WithMany()
                        .HasForeignKey("LokasiParkirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemRetribusiParkir.Models.Petugas", "Petugas")
                        .WithMany("Retribusi")
                        .HasForeignKey("PetugasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JenisKendaraan");

                    b.Navigation("LokasiParkir");

                    b.Navigation("Petugas");
                });

            modelBuilder.Entity("SistemRetribusiParkir.Models.JenisKendaraan", b =>
                {
                    b.Navigation("Retribusi");
                });

            modelBuilder.Entity("SistemRetribusiParkir.Models.Petugas", b =>
                {
                    b.Navigation("Retribusi");
                });
#pragma warning restore 612, 618
        }
    }
}
